const TOKEN = "TOKEN";
const LOADER = "LOADER";
const ACTIONMESSAGE = "ACTIONMESSAGE";
const GETHOMEPAGEDATA = "GETHOMEPAGEDATA";
const MAINTENANCE = "MAINTENANCE";
const PAGELOADER = "PAGELOADER";
const USERDATA = "USERDATA";
const ISLOGGEDUSER = "ISLOGGEDUSER";
const PRODUCTDATA = "PRODUCTDATA";
const PRODUCTLISTDATA = "PRODUCTLISTDATA";
const FILTERDATA = "FILTERDATA";
const PRICEFILTER = "PRICEFILTER";
const QUICKVIEW = "QUICKVIEW";
const QUICKVIEWDATA = "QUICKVIEWDATA";
const CARTCOUNT = "CARTCOUNT";
const MINICARTDATA = "MINICARTDATA";
const MINIQUOTEDATA = "MINIQUOTEDATA";
const GUESTCARTTOKEN = "GUESTCARTTOKEN";
const UPDATECART = "UPDATECART";
const UPDATEQUOTE = "UPDATEQUOTE";
const MYACCOUNTCURRENTPAGE = "MYACCOUNTCURRENTPAGE";
const ISLOADING = "ISLOADING";
const SCROLLTOTOP = "SCROLLTOTOP";
const NOTIFYMEPOPUP = "NOTIFYMEPOPUP";
const PAGEMESSAGE = "PAGEMESSAGE";
const PLPFILTERPARAMS = "PLPFILTERPARAMS";
const SEARCHFILTERPARAMS = "SEARCHFILTERPARAMS";
const UPDATEFILTER = "UPDATEFILTER";
const WISHLISTDATA = "WISHLISTDATA";
const UPDATEWISHLIST = "UPDATEWISHLIST";
const COUNTRYLIST = "COUNTRYLIST";
const ISCOUNTRYSELECTED = "ISCOUNTRYSELECTED";
const STATESLIST = "STATESLIST";
const COUNTRYCODE = "COUNTRYCODE";
const WPAGESIZE = "WPAGESIZE";
const WCURRENTPAGE = "WCURRENTPAGE";
const GUESTSHIPPING = "GUESTSHIPPING";
const GUESTVALIDSHIPPING = "GUESTVALIDSHIPPING";
const GUESTBILLING = "GUESTBILLING";
const SHIPPINGMETHODDETAILS = "SHIPPINGMETHODDETAILS";
const LOGGEDINUSERDATA = "LOGGEDINUSERDATA";
const UPDATEACCOUTUSERDATA = "UPDATEACCOUTUSERDATA";
const CREATECARTID = "CREATECARTID";
const CURRENCY = "CURRENCY";
const ESTIMATESHIPPINGMETHOD = "ESTIMATESHIPPINGMETHOD";
const ISGUESTCARTDATA = "ISGUESTCARTDATA";
const WISHLISTPRODUCTID = "WISHLISTPRODUCTID";
const SHOWAUTHENTICATIONPOPUP = "SHOWAUTHENTICATIONPOPUP";
const GROUPEDFROMWISHLISTTOCART = "GROUPEDFROMWISHLISTTOCART";
const RECENTSEARCH = "RECENTSEARCH";
const PREVIOUSURL = "PREVIOUSURL";
const GUESTSAMEASSHIPPINGBILLING = "GUESTSAMEASSHIPPINGBILLING";
const GUESTSAVEDBILLINGADDRESS = "GUESTSAVEDBILLINGADDRESS";
const SEARCHEDTEXT = "SEARCHEDTEXT";
const ISSEARCHRESULT = "ISSEARCHRESULT";
const CARTDATA_ADDRESS = "CARTDATA_ADDRESS";
const CUSTOMERSAMEASSHIPPING = "CUSTOMERSAMEASSHIPPING";
const HOMEAPILOADER = "HOMEAPILOADER";
const SELECTED_PAYMENTMETHOD = "SELECTED_PAYMENTMETHOD";
const IS_ORDER_COMPLETE = "IS_ORDER_COMPLETE";
export {
    TOKEN, LOADER, MAINTENANCE, GETHOMEPAGEDATA, PAGELOADER,
    USERDATA, ISLOGGEDUSER, ACTIONMESSAGE, PRODUCTDATA, PRODUCTLISTDATA,
    FILTERDATA, PRICEFILTER, QUICKVIEW, QUICKVIEWDATA, CARTCOUNT,
    MINICARTDATA, GUESTCARTTOKEN, UPDATECART, MYACCOUNTCURRENTPAGE,
    ISLOADING, SCROLLTOTOP, NOTIFYMEPOPUP, PAGEMESSAGE, PLPFILTERPARAMS,
    UPDATEFILTER, WISHLISTDATA, UPDATEWISHLIST, COUNTRYLIST, ISCOUNTRYSELECTED,
    STATESLIST, COUNTRYCODE, WPAGESIZE, WCURRENTPAGE, GUESTSHIPPING, GUESTVALIDSHIPPING,
    GUESTBILLING, SHIPPINGMETHODDETAILS, LOGGEDINUSERDATA, UPDATEACCOUTUSERDATA,
    CREATECARTID, CURRENCY, ESTIMATESHIPPINGMETHOD, ISGUESTCARTDATA, WISHLISTPRODUCTID,
    SHOWAUTHENTICATIONPOPUP, SEARCHFILTERPARAMS, GROUPEDFROMWISHLISTTOCART, RECENTSEARCH,
    PREVIOUSURL, GUESTSAMEASSHIPPINGBILLING, GUESTSAVEDBILLINGADDRESS, SEARCHEDTEXT,
    ISSEARCHRESULT, CARTDATA_ADDRESS, CUSTOMERSAMEASSHIPPING, HOMEAPILOADER,
    SELECTED_PAYMENTMETHOD, IS_ORDER_COMPLETE,MINIQUOTEDATA,UPDATEQUOTE
};