name: Node.js CI

on:
  push:
    branches: [ "jenkins" ]
    
jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    # Install dependencies with legacy-peer-deps flag to bypass conflicts
    - name: Install dependencies
      run: npm install --legacy-peer-deps
    
    # Build the project
    - name: Build project
      run: npm run build --if-present
